[build]
xargo = true

[target.armv7-unknown-linux-gnueabihf]
image = "japaric/arm-linux"

[target.i686-unknown-linux-gnu]
image = "japaric/i686-linux"

[target.x86_64-unknown-linux-gnu]
image = "japaric/x86_64-linux"
